### PR TITLE
try to fix #874, but not working

### LINKED ISSUE #874: 未登入可以執行DELETE指令
用指令 `curl "http://beta.labfnp.com/api/admin/upload/<別人的圖片檔名不含.jpg>?" -X DELETE` 就可以刪除，訊息是Success

不過因為刪除檔案還沒實作，所以目前不會真的刪掉

### PR DESCRIPTION
**Pull request by dd-han**
not working!!!

### CODE REVIEW

**Comment by FuYaoDe** [comment]
修正  customConfigLoader('policies.js') 就 OK 了 可能複製時沒複製好

**Comment by FuYaoDe** [comment]
https://github.com/balderdashy/sails/issues/887#issuecomment-36300347
試試看裡面提到的方法

**Comment by FuYaoDe** [comment]
https://groups.google.com/forum/#!msg/sailsjs/uRCw0iowhwY/dSF8YkC0AckJ

**Comment by smlsunxie** [comment]
參考 https://groups.google.com/forum/#!msg/sailsjs/uRCw0iowhwY/dSF8YkC0AckJ

**Pull request merged**
